parameters:
#    jan_moc_demo.example.class: Jan\MOCDemoBundle\Example

services:
#    jan_moc_demo.example:
#        class: %jan_moc_demo.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
